blog/urls.py
from django.urls import path
from .views import BlogIndex,  PostDetail,  AddPostView, UpdatePostView,  DeletePostView, AddCategoryView
from .import views

#from .feeds import LatestPostsFeed



app_name= 'blog'

urlpatterns = [
    path('blog', views.BlogIndex, name="blogIndex"),
    
    #path('post/<int:pk>', PostDetail.as_view(), name="postDetail"),

    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.PostDetail, name="postDetail" ),
    path('<int:post_id>/share/',views.post_share, name='post_share'),
    
    path('add_post/', AddPostView.as_view(), name="add_post"),

    #path('add_category/', AddCategoryView.as_view(), name="add_category"),

    path('post/edit/<int:pk>', UpdatePostView.as_view(), name="update_post"),
    
    
    path('post/<int:pk>/remove', DeletePostView.as_view(), name="deletepost"),
    
   # path('category/<str:cats>/', CategoryView, name='category'),
    
   # path('like/<int:pk>', LikeView, name='like_post'),
    path('tag/<slug:tag_slug>/' ,views.BlogIndex, name='blogIndex_by_tag'),

    #path('feed/', LatestPostsFeed(), name='post_feed'),
    
    path('search/',views.postSearch, name='search'),
    

]

mosay360/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib.auth import views as auth_views
from django.contrib import admin
from  members.forms import LoginForm
from members.views import CustomLoginView, ResetPasswordView, ChangePasswordView
from django.urls import path, include, re_path

urlpatterns = [
    
    path('admin/', admin.site.urls),
    path('', include ('home.urls')),
    
    path('blog/', include('blog.urls', namespace='blog')),
    path("i18n/", include("django.conf.urls.i18n")),
    
    path('members/', include('django.contrib.auth.urls')),
    path('members/', include('members.urls')),
    
    path('login/', CustomLoginView.as_view(redirect_authenticated_user=True, template_name='registration/login.html',
                                           authentication_form=LoginForm), name='login'),

    path('logout/', auth_views.LogoutView.as_view(template_name='registration/logout.html'), name='logout'),

    path('password-reset/', ResetPasswordView.as_view(), name='password_reset'),

    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html'),
         name='password_reset_confirm'),

    path('password-reset-complete/',auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
         name='password_reset_complete'),

    path('password-change/', ChangePasswordView.as_view(), name='password_change'),

    re_path(r'^oauth/', include('social_django.urls', namespace='social')),

]
urlpatterns = urlpatterns + \
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/fragments/base.html

{% load blog_tags %} 
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>wwwws</title>
    <meta content="" name="description">
    <meta content ="" name="keywords">

     <!-- Favicons -->
  <link href="{% static 'img/favicon.png' %}" rel="icon">
  <link href="{% static 'img/apple-touch-icon.png' %}" rel="apple-touch-icon">
<!-- CDN -->


  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Roboto:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static 'vendor/animate.css/animate.min.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/aos/aos.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/remixicon/remixicon.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="{% static 'css/style.css' %}" rel="stylesheet">
  <link href ="{% static 'css/styles.css' %}" rel="stylesheet">

  <!-- =======================================================
  * Template Name: Company - v4.8.0
  * Template URL: https://bootstrapmade.com/company-free-html-bootstrap-template/
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
    
   
</head>
<body>
    {% block  content %} {% endblock %}
</body>
</html>

templates/fragments/footer.html
 <!-- ======= Footer ======= -->

 
 <footer id="footer">

    <div class="footer-top">
      <div class="container">
        <div class="row">

          <div class="col-lg-3 col-md-6 footer-contact">
            <h3>Mosay360</h3>
            <p>
              Kumasi Adom  Police Station <br>
              Adum Railways  ST 102<br>
              Ghana  <br><br>
              <strong>Phone:</strong> +233(0)247765596<br>
              <strong>Email:</strong> mosay360@gmail.com<br>
            </p>
          </div>

          <div class="col-lg-2 col-md-6 footer-links">
            <h4>Useful Links</h4>
            <ul>
              <li><i class="bx bx-chevron-right"></i> <a href="/">Home</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">About us</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="/services">Services</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Terms of service</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Privacy policy</a></li>
            </ul>
          </div>

          <div class="col-lg-3 col-md-6 footer-links">
            <h4>Our Services</h4>
            <ul>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Architectural Drawing</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Reroofing</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Wood Installation</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Roofing Installation</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Roofing Estimation</a></li>
            </ul>
          </div>

          <div class="col-lg-4 col-md-6 footer-newsletter">
            <h4>Subscribe To Our Newsletter</h4>
            <p>At Mosay360, Your family needs always comes first before anything else</p>
            <form action="" method="post">
              <input type="email" name="email"><input type="submit" value="Subscribe">
            </form>
          </div>

        </div>
      </div>
    </div>

    <div class="container d-md-flex py-4">

      <div class="me-md-auto text-center text-md-start">
        <div class="copyright">
          &copy; Copyright <strong><span>Company</span></strong>. All Rights Reserved
        </div>
        <div class="credits">
          <!-- All the links in the footer should remain intact. -->
          <!-- You can delete the links only if you purchased the pro version. -->
          <!-- Licensing information: https://bootstrapmade.com/license/ -->
          <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/company-free-html-bootstrap-template/ -->
          Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
        </div>
      </div>
      <div class="social-links text-center text-md-right pt-3 pt-md-0">
        <a href="#" class="twitter"><i class="bx bxl-twitter"></i></a>
        <a href="#" class="facebook"><i class="bx bxl-facebook"></i></a>
        <a href="#" class="instagram"><i class="bx bxl-instagram"></i></a>
        <a href="#" class="google-plus"><i class="bx bxl-skype"></i></a>
        <a href="#" class="linkedin"><i class="bx bxl-linkedin"></i></a>
      </div>
    </div>
  </footer><!-- End Footer -->

  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>


  {% load static %}
  <!-- Vendor JS Files -->
  <script src="{% static 'vendor/aos/aos.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'vendor/glightbox/js/glightbox.min.js' %}"></script>
  <script src="{% static 'vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
  <script src="{% static 'vendor/swiper/swiper-bundle.min.js' %}"></script>
  <script src="{% static 'vendor/waypoints/noframework.waypoints.js' %}"></script>
  <script src="{% static 'vendor/php-email-form/validate.js' %}"></script>

  <!-- Template Main JS File -->
  <script src="{% static 'js/main.js' %}"></script>
  <script src= "{% static 'js/mains.js'%}"></script>

templates/fragments/nav.html
 <!-- ======= Header ======= -->
 <header id="header" class="fixed-top">
  <div class="container d-flex align-items-center">

    <h1 class="logo me-auto"><a href="/"><span>Mosay</span>360</a></h1>
    <!-- Uncomment below if you prefer to use an image logo -->
    <!-- <a href="index.html" class="logo me-auto me-lg-0"><img src="assets/img/logo.png" alt="" class="img-fluid"></a>-->

    <nav id="navbar" class="navbar order-last order-lg-0">
      <ul>
        <li><a href="/" class="active">Home</a></li>

        <li class="dropdown"><a href="#"><span>About</span> <i class="bi bi-chevron-down"></i></a>
          <ul>
            <li><a href="about.html">About Us</a></li>
            <li><a href="team.html">Team</a></li>
            <li><a href="testimonials.html">Testimonials</a></li>
            <li class="dropdown"><a href="#"><span>Deep Drop Down</span> <i class="bi bi-chevron-right"></i></a>
              <ul>
                <li><a href="#">Deep Drop Down 1</a></li>
                <li><a href="#">Deep Drop Down 2</a></li>
                <li><a href="#">Deep Drop Down 3</a></li>
                <li><a href="#">Deep Drop Down 4</a></li>
                <li><a href="#">Deep Drop Down 5</a></li>
              </ul>
            </li>
          </ul>
        </li>

        {% comment %}  
        <li><a href="/service">Services</a></li>
        {% endcomment %}





        {% comment %} Dropdown for Services {% endcomment %}


<li class="dropdown"><a href="#"><span>Services</span> <i class="bi bi-chevron-down"></i></a>
          <ul>
            <li><a href="/service">Our Services</a></li>
            <li><a href="team.html">Team</a></li>
            <li><a href="testimonials.html">Testimonials</a></li>
            <li class="dropdown"><a href="#"><span>Service Details</span> <i class="bi bi-chevron-right"></i></a>
              <ul>
                <li><a href="#">Roofing Estimation</a></li>
                <li><a href="#">Wood Installation</a></li>
                <li><a href="#">Reroofing</a></li>
                <li><a href="#">Free Estimation</a></li>
                <li><a href="#">Architectural Drawing</a></li>
              </ul>
            </li>
          </ul>
        </li>


        {% comment %} End of service dropdown {% endcomment %}
        <li><a href="/portfolio">Products</a></li>
        <li><a href="pricing.html">Pricing</a></li>
        <li><a href="{% url 'blog:blogIndex' %}">Blog</a></li>
        <li><a href="contact.html">Contact</a></li>


        
          <li class="dropdown"><a href="#"><span>User Account</span> <i class="bi bi-chevron-down"></i></a>
            <ul>
              {% if user.is_authenticated %}
              <li><a href="{% url 'blog:add_post' %}">Add Post</a></li>
              <li><a href= "{% url 'profile' %}">Profile</a></li>
              <li><a href="{% url 'logout' %}">Logout</a></li>

              {% else %}
              <li><a href="{% url 'register' %}">Register</a></li>
              <li><a href="{% url 'login' %}">Login</a></li>
               {% endif %}
              
            </ul>
          </li>
  
        

      </ul>
      <i class="bi bi-list mobile-nav-toggle"></i>
<!--dropdown begin-->
      
     
<!--dropdown  end-->

    </nav><!-- .navbar -->

    <div class="header-social-links d-flex">
      

      {% if user.is_authenticated %}
      &nbsp; <i style = "color:cadetblue;">Welcome, {{user.username| capfirst}}</i>
     {% endif %}
      <a href="#" class="facebook"><i class="bu bi-facebook"></i></a>
     
      
    </div>

  </div>
</header><!-- End Header -->

templates/fragments/testimony.html
{% load blog_tags %}
{% load static %}

  <!-- ======= Testimonials Section ======= -->
  <section id="services" class="services section-bg">

    <div class="container" data-aos="fade-up">

        <div class="section-title">
          <h2><strong>Testimonies</strong></h2>
          <p>Laborum repudiandae omnis voluptatum consequatur mollitia ea est voluptas ut</p>
        </div>


      <div id="testimonial-carousel" class="swiper">
        <div class="swiper-wrapper">

          <div class="carousel-item-a swiper-slide">
            <div class="testimonials-box">
              <div class="row">
                <div class="col-sm-12 col-md-6">
                  <div class="testimonial-img">
                    <img src="{% static 'img/testimonial-1.jpg' %}" alt="" class="img-fluid">
                  </div>
                </div>
                <div class="col-sm-12 col-md-6">
                  <div class="testimonial-ico">
                    <i class="bi bi-chat-quote-fill"></i>
                  </div>
                  <div class="testimonials-content">
                    <p class="testimonial-text">
                      Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis, cupiditate ea nam praesentium
                      debitis hic ber quibusdam
                      voluptatibus officia expedita corpori.
                    </p>
                  </div>
                  <div class="testimonial-author-box">
                    <img src="{% static 'img/mini-testimonial-1.jpg' %}" alt="" class="testimonial-avatar">
                    <h5 class="testimonial-author">Albert & Erika</h5>
                  </div>
                </div>
              </div>
            </div>
          </div><!-- End carousel item -->

          <div class="carousel-item-a swiper-slide">
            <div class="testimonials-box">
              <div class="row">
                <div class="col-sm-12 col-md-6">
                  <div class="testimonial-img">
                    <img src="{%static 'img/testimonial-2.jpg' %}" alt="" class="img-fluid">
                  </div>
                </div>
                <div class="col-sm-12 col-md-6">
                  <div class="testimonial-ico">
                    <i class="bi bi-chat-quote-fill"></i>
                  </div>
                  <div class="testimonials-content">
                    <p class="testimonial-text">
                      Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis, cupiditate ea nam praesentium
                      debitis hic ber quibusdam
                      voluptatibus officia expedita corpori.
                    </p>
                  </div>
                  <div class="testimonial-author-box">
                    <img src="{% static 'img/mini-testimonial-2.jpg' %}" alt="" class="testimonial-avatar">
                    <h5 class="testimonial-author">Pablo & Emma</h5>
                  </div>
                </div>
              </div>
            </div>
          </div><!-- End carousel item -->




          <div class="carousel-item-a swiper-slide">
            <div class="testimonials-box">
              <div class="row">
                <div class="col-sm-12 col-md-6">
                  <div class="testimonial-img">
                    <img src="{%static 'img/testimonial-2.jpg' %}" alt="" class="img-fluid">
                  </div>
                </div>
                <div class="col-sm-12 col-md-6">
                  <div class="testimonial-ico">
                    <i class="bi bi-chat-quote-fill"></i>
                  </div>
                  <div class="testimonials-content">
                    <p class="testimonial-text">
                      Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis, cupiditate ea nam praesentium
                      debitis hic ber quibusdam
                      voluptatibus officia expedita corpori.
                    </p>
                  </div>
                  <div class="testimonial-author-box">
                    <img src="{% static 'img/mini-testimonial-2.jpg' %}" alt="" class="testimonial-avatar">
                    <h5 class="testimonial-author">Pablo & Emma</h5>
                  </div>
                </div>
              </div>
            </div>
          </div><!-- End carousel item -->

        </div>
      </div>
      <div class="testimonial-carousel-pagination carousel-pagination"></div>

    </div>
  </section><!-- End Testimonials Section -->