blog/urls.py
from django.urls import path
from .views import BlogIndex,  PostDetail,  AddPostView, UpdatePostView,  DeletePostView, AddCategoryView
from .import views

#from .feeds import LatestPostsFeed



app_name= 'blog'

urlpatterns = [
    path('blog', views.BlogIndex, name="blogIndex"),
    
    #path('post/<int:pk>', PostDetail.as_view(), name="postDetail"),

    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.PostDetail, name="postDetail" ),
    path('<int:post_id>/share/',views.post_share, name='post_share'),
    
    path('add_post/', AddPostView.as_view(), name="add_post"),

    #path('add_category/', AddCategoryView.as_view(), name="add_category"),

    path('post/edit/<int:pk>', UpdatePostView.as_view(), name="update_post"),
    
    
    path('post/<int:pk>/remove', DeletePostView.as_view(), name="deletepost"),
    
   # path('category/<str:cats>/', CategoryView, name='category'),
    
   # path('like/<int:pk>', LikeView, name='like_post'),
    path('tag/<slug:tag_slug>/' ,views.BlogIndex, name='blogIndex_by_tag'),

    #path('feed/', LatestPostsFeed(), name='post_feed'),
    
    path('search/',views.postSearch, name='search'),
    

]

mosay360/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib.auth import views as auth_views
from django.contrib import admin
from  members.forms import LoginForm
from members.views import CustomLoginView, ResetPasswordView, ChangePasswordView
from django.urls import path, include, re_path

urlpatterns = [
    
    path('admin/', admin.site.urls),
    path('', include ('home.urls')),
    
    path('blog/', include('blog.urls', namespace='blog')),
    path("i18n/", include("django.conf.urls.i18n")),
    
    path('members/', include('django.contrib.auth.urls')),
    path('members/', include('members.urls')),
    
    path('login/', CustomLoginView.as_view(redirect_authenticated_user=True, template_name='registration/login.html',
                                           authentication_form=LoginForm), name='login'),

    path('logout/', auth_views.LogoutView.as_view(template_name='registration/logout.html'), name='logout'),

    path('password-reset/', ResetPasswordView.as_view(), name='password_reset'),

    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html'),
         name='password_reset_confirm'),

    path('password-reset-complete/',auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
         name='password_reset_complete'),

    path('password-change/', ChangePasswordView.as_view(), name='password_change'),

    re_path(r'^oauth/', include('social_django.urls', namespace='social')),

]
urlpatterns = urlpatterns + \
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
import email
from django.utils import timezone
from django.db import models
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField
from django.urls import reverse
from django.db import models
from taggit.managers import TaggableManager
# Create your models here.
class PublishedManager(models.Manager):
    def get_queryset(self):
        
        return super(PublishedManager, self).get_queryset().filter(status= 'published')
    
    
    

class Post(models.Model):
        STATUS_CHOICE= (
            ('draft', 'Draft'),
            ('published', 'Published'),
        )
        title = models.CharField(max_length=250)
        tags = TaggableManager()
        slug = models.SlugField(max_length=250,unique_for_date='publish')
        author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts')
        blockImage = models.ImageField(upload_to='blogImage', null=True , blank=True)
        body = RichTextField(blank=True, null=True)
        publish = models.DateTimeField(default = timezone.now)
        created = models.DateTimeField(auto_now=True)
        updated = models.DateTimeField(auto_now=True)
        status = models.CharField(max_length=10, choices=STATUS_CHOICE, default='draft')
        objects = models.Manager()
        
        published = PublishedManager()
        
    
        class Meta:
            ordering = ('-publish',)
        def __str__(self):
             return self.title
        
        
        def get_absolute_url(self):
            return reverse('blog:postDetail', args=[
            self.publish.year, self.publish.month, self.publish.day, self.slug
            ])
        
        # Model for comments


class Comment(models.Model):
    post= models.ForeignKey(Post, on_delete=models.CASCADE, related_name ='comments')
    name = models.CharField(max_length=250)
    email= models.EmailField()
    body = RichTextField(blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default= True)
    
    
    class Meta:
        ordering = ('created',)
    def __str__(self):
     return f'Comment by {self.name} on {self.post}'

class Slider(models.Model):
    slideImage= models.ImageField(upload_to='SlidePic')
    title = models.CharField(max_length=250)
    created = models.DateTimeField(auto_now_add= True)
    body = RichTextField(blank=True, null=True)
        

blog/forms.py
from distutils.command.upload import upload
from email.policy import default

from django import forms
from django.forms import ModelForm, widgets
from .models import Post
from .models import Comment

# create a post form


choices = [('coding', 'coding'), ('sport', 'sport'), ('programming', 'programming'), ]







class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('title', 'slug', 'author',
                   'body')

        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'slug': forms.TextInput(attrs={'class': 'form-control'}),
            'author': forms.TextInput(attrs={'class': 'form-control', 'value': '', 'id': 'elder', 'type': 'hidden'}),
            #'category': forms.Select(choices= choices, attrs={'class': 'form-control'}),
           # 'blogImage':forms.ImageField(attrs={'class':'form-control'}),
            'body': forms.Textarea(attrs={'class': 'form-control'}),
            # 'snippet': forms.Textarea(attrs={'class': 'form-control'}),
            
        }


class EditForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('title', 'slug',  'body')

        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'slug': forms.TextInput(attrs={'class': 'form-control'}),
            #'category':forms.Select(attrs={'class':'form-control'}),
            'body': forms.Textarea(attrs={'class': 'form-control'}),
            # 'snippet': forms.Textarea(attrs={'class': 'form-control'}),
        }
class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email= forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name','email', 'body')
        
    widgets = {
        'name': forms.TextInput(attrs={'class':'form-control'}),
        'email':forms.TextInput(attrs={'class':'form-control'}),
        'body': forms.Textarea(attrs={'class':'form-control'}),
    }
class SearchForm(forms.Form):
    query = forms.CharField()

blog/views.py
from django.shortcuts import render
from django.contrib.postgres.search import  SearchVector
from email import message
from multiprocessing import context
from re import search
from django.http.response import HttpResponseRedirect
from django.urls.base import reverse
from blog.models import Post, Comment
from typing import List
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from .models import Post
from django.contrib.postgres.search import SearchVector
from .forms import CommentForm, PostForm, EditForm , EmailPostForm 
from django.urls import reverse_lazy, reverse
from django.http import HttpResponseRedirect
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .forms import EmailPostForm ,CommentForm
from django.core.mail import send_mail
from taggit.models import Tag
from django.db.models import Count

# Create your views here.


def BlogIndex(request, tag_slug=None):
    object_list= Post.published.all()
    ordering=['-publish']
    tag= None
    if tag_slug:
        tag= get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in = [tag])
    paginator= Paginator(object_list, 3)
    page= request.GET.get('page')
    try:

        posts = paginator.page(page)
    except PageNotAnInteger:
        posts= paginator.page(1)
    except EmptyPage:
        posts =paginator.page(paginator.num_pages)

       

    return render(request, 'blog/blogIndex.html',
    {'page':page, 'posts':posts, 
    'tag':tag
    }
    )
    
    
def Blog( request):
    
    return render(request, 'blogIndex.html')

    
    
 #Detail views
def PostDetail(request, year, month, day, post):
    post=get_object_or_404(
    Post, slug=post,
    status='published',
    publish__year=year,
    publish__month=month,
    publish__day=day
    )


    #List of active comments for this post

    comments = post.comments.filter(active=True)
    new_comment = None
    comment_form = CommentForm(data=request.POST)
    if request.method == 'POST':
        #posted comment
       
      if comment_form.is_valid():

        new_comment = comment_form.save(commit=False)
        new_comment.post= post
        new_comment.save()
    else: 
        comment_form = CommentForm()


        post_tags_ids = post.tags.values_list('id', flat=True)
        similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
        similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags','-publish')[:4]
    return render(request, 'blog/postDetail.html',{'post':post, 'new_comment':new_comment, 'comments':comments, 'comment_form':comment_form,
    })

def post_share(request, post_id):

    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False    


    if request.method == 'POST':
        form = EmailPostForm(request.POST)
        if form.is_valid():
            cd= form.cleaned_data
        post_url = request.build_absolute_uri(
        post.get_absolute_url())
        subject = f"{cd['name']} recommends you read " 
        f"{post.title}"
        message = f"Read {post.title} at {post_url}" 
        f"{cd['name']}'s comments: {cd['comments']}"
        send_mail(subject, message, 'mosay360@gmail.com', [cd['to']])
        sent = True
    else: 
            form = EmailPostForm()
    return render(request, 'blog/share.html',{'post':post, 'form':form
    ,'sent':sent})




#def blogIndex(request):

   # object_list = Post.published.all()
    #ordering = ['-publish']
   # paginator= Paginator(object_list, 3)
    #page = request.GET.get('page')
    #try:
       # posts= paginator.page(page)
   # except PageNotAnInteger:
       # posts= paginator.page(1)
    #except EmptyPage:
       # posts=paginator.page(paginator.num_pages)

   # return render(request, 'blog/blogIndex.html',{'page':page,'posts':posts})


class BlogView(ListView):
    model = Post
    template_name = 'blog/blogIndex.html'
    ordering = ['-created']



class AddPostView(CreateView):
    model = Post
    form_class = PostForm
    template_name = 'blog/add_post.html'

    #fields ='__all__'


class AddCategoryView(CreateView):
    
    #form_class = PostForm
    template_name = 'blog/add_category.html'
    fields = '__all__'


class UpdatePostView(UpdateView):
    model = Post
    form_class = EditForm
    template_name = 'blog/update_post.html'
    #fields =['title','title_tag', 'body']


class DeletePostView(DeleteView):
    model = Post
    template_name = 'blog/delete_post.html'
    success_url = reverse_lazy('blog:blogIndex')

def postSearch(request):
    
    if request.method == "POST":
        searched = request.POST['searched']
        posts= Post.objects.filter(body__contains=searched )
        

        return render(request, 
        'blog/search.html',{'searched':searched, 'posts':posts})
    else:
         return render(request, 
        'blog/search.html',{})

def Slider(request):
    slide = Slider.object.all()
    context ={
        'slider':Slider
    }  
    return render(request, "blog/slider.html")

templates/blog/add_post.html
{% extends 'fragments/base.html' %}
{% load blog_tags %}
{% block content %}
 {% include 'fragments/nav.html' %}
 
<main id="main">

    <!-- ======= Breadcrumbs ======= -->
    <section id="breadcrumbs" class="breadcrumbs">
      <div class="container">

        <div class="d-flex justify-content-between align-items-center">
          <h2>Add Blog Post  </h2>
          <ol>
            <li><a href="/">Home</a></li>
            <li> <a href="{% url 'blog:blogIndex' %}">Blog</a></li>
          </ol>
        </div>

      </div>
    </section><!-- End Breadcrumbs -->

    <!-- ======= Blog Section ======= -->
    <section id="blog" class="blog">
      <div class="container-fluid">

        <div class="row">

          <div class="col-lg-8 entries">
                
            

            <article class="entry" data-aos="fade-up">

              <div class="entry-img">
                <img src="assets/img/blog-2.jpg" alt="" class="img-fluid">
              </div>

              <h2 class="entry-title">
                <a href="blog-single.html">Add Blog Post </a>
              </h2>

              <div class="entry-meta">
                <ul>
                  <li class="d-flex align-items-center"><i class="icofont-user"></i> <a href="blog-single.html">John Doe</a></li>
                  <li class="d-flex align-items-center"><i class="icofont-wall-clock"></i> <a href="blog-single.html"><time datetime="2020-01-01">Jan 1, 2020</time></a></li>
                  <li class="d-flex align-items-center"><i class="icofont-comment"></i> <a href="blog-single.html">12 Comments</a></li>
                </ul>
              </div>

              <div class="entry-content">
                {% if user.is_authenticated %}
              <div class= "form-group">
                   <form method="POST" >
                       {% csrf_token %}
                       {{ form.media }}
                        {{ form.as_p }}
                        <button class="btn btn-primary">Post</button>
                   
                   </form>
                </div>
                {% else %}
                <h3>You are not allow to add post here </h3>
                <br/>
                
                <h3><a href="{% url 'login' %}">Login</a> </h3> OR <br/>
                 <h3><a href="{% url 'register' %}">Register</a> For New Account</h3>

                {% endif %}
                <!-- Javascript -->
                <script>
                   var name ="{{user.id}}";
                   document.getElementById("elder").value= name;
                </script>


                <div class="read-more">
                  <a href="blog-single.html">Read More</a>
                </div>
              </div>
            
            </article><!-- End blog entry -->

          </div><!-- End blog entries list -->

          
          <div class="col-lg-4">

            <div class="sidebar" data-aos="fade-left">

              <h3 class="sidebar-title">Search</h3>
              <div class="sidebar-item search-form">
               
                <form action="{% url 'blog:search' %}" method=POST>
                  {% csrf_token %}
                  <input type="search" class = "form-control " name="searched"  placeholder="search post">
                  <button type="submit"><i class="icofont-search"></i></button>
                </form>
              </div><!-- End sidebar search formn-->

              <h3 class="sidebar-title">Recent Posts</h3>
              <div class="sidebar-item recent-posts">
                <div class="post-item clearfix">
                  
                  {% show_latest_posts 5 %}
                  
                </div>


               

              </div><!-- End sidebar recent posts-->

              <h3 class="sidebar-title">Tags</h3>
              <div class="sidebar-item tags">
                <ul>
                  <li><h2>Similar posts</h2>
                    {% for post in similar_posts %}
                    <p>
                    <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                    </p>
                    {% empty %}
                    There are no similar posts yet.
                    {% endfor %}</li>
                  
                </ul>

              </div><!-- End sidebar tags-->
              
              <div class="post-item clearfix">
                <h3 class="sidebar-title">Most Commented Posts</h3>
            
              {% get_most_commented_posts as most_commented_posts %}
              <ul class="text-decoration-none">
              {% for post in most_commented_posts %}
              <li>
              <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
              </li>
              {% endfor %}
              </ul>

              </div>
            </div><!-- End sidebar -->

          </div><!-- End blog sidebar -->

        </div>

      </div>
    </section><!-- End Blog Section -->

  </main><!-- End #main -->

  <!-- ======= Footer ======= -->
 
    {% include 'fragments/footer.html' %}
  {% endblock%}

templates/blog/blogIndex.html
{% extends 'fragments/base.html' %}

{% load blog_tags %}
{% block content %}
 {% include 'fragments/nav.html' %}
 
<main id="main">

    <!-- ======= Breadcrumbs ======= -->
    <section id="breadcrumbs" class="breadcrumbs">
      <div class="container">

        <div class="d-flex justify-content-between align-items-center">
          <h2>Blog</h2>
          <ol>
            <li><a href="/">Home</a></li>
           {% if user.is_authenticated %}
            <li><a href="{% url 'blog:add_post' %}">Add Post </a></li> 
         {% endif %}
            <li>Blog</li>
          </ol>
        </div>

      </div>
    </section><!-- End Breadcrumbs -->

    <!-- ======= Blog Section ======= -->
    <section id="blog" class="blog">
      <div class="container">

      <div class="row">

          <div class="col-lg-8 entries">
            
                  {% for post in posts %}
              <article class="entry" data-aos="fade-up">
            
              <div class="entry-img">
                <img src="{{ post.blockImage.url }}" alt="" height="400px" width="800px">
                <img src="assets/img/blog-1.jpg" alt="" class="img-fluid">
              </div>

              <h2 class="entry-title">
                  {% block title%}{{post.title}}{% endblock%}
                </a>
              </h2>
              
              <div class="entry-meta">
                <ul>
                  <li class="d-flex align-items-center">
                   </i> <a href="blog-single.html">{{post.author}} {{post.id}}</a></li>
                   <li class="d-flex align-items-center"><i class="icofont-user"></i> <a href="{{ post.get_absolute_url }}">{{post.title}}</a></li> 
                   
                  {% if user.is_authenticated %}
                 
                  {% if user.id == post.author.id %}

                  <li><i class="fa fa-pencil-square-o" aria-hidden="true"></i><a href="{%  url 'blog:update_post' post.pk %}">Edit Post</a></li>

                 <li><i class="fa fa-trash" aria-hidden="true"></i><a href="{% url 'blog:deletepost' post.pk %}">Delete Post</a></li>

                 {% endif %}
                 {%endif%}
                  <li class="d-flex align-items-center"><i class="icofont-wall-clock"></i> <a href="blog-single.html"><time datetime="2020-01-01">{{post.created}}</time></a></li>
                  <li class="d-flex align-items-center"><i class="icofont-comment"></i> <a href="blog-single.html">12 Comments</a></li>

                 
                  <!--Forms goes here-->
                </ul>
                
              </div>

              <div class="entry-content ">
                

                <P class="date">
                  Published {{ post.publish }} By {{ post.author }}
                </P>

                <p >
                 <!-- {{post.snippet}} -->
                  {{ post.body|markdown|truncatechars_html:200|safe }}
                </p>
               
                <div class="read-more">  
                  <a href="{{ post.get_absolute_url }}">Read More</a>
                </div>

              </div>
               
            </article><!-- End blog entry -->
           {% endfor %}
           



            <!--Pagination here-->
            {% include "blog/pagination.html" with page=posts %}
          </div><!-- End blog entries list -->






          <div class="col-lg-4">

            <div class="sidebar" data-aos="fade-left">

              <h3 class="sidebar-title">Search</h3>
              <div class="sidebar-item search-form">



                 <form action="{% url 'blog:search' %}" method=POST>
                  {% csrf_token %}
                  <input type="text" >
                  <button type="submit"><i class="bi bi-search"></i></button>
                </form>

              </div>
              <!-- End sidebar search form--> 

              <h3 class="sidebar-title">Recent Posts</h3>
              <div class="sidebar-item recent-posts">
                <div class="post-item clearfix">
                  
                  {% show_latest_posts 8 %}
                  
                </div>

                <!--<div class="post-item clearfix">
                  <img src="assets/img/blog-recent-posts-5.jpg" alt="">
                  <time datetime="2020-01-01">Jan 1, 2020</time>
                </div> -->

              </div><!-- End sidebar recent posts-->


              <div class="post-item clearfix">
                <h3 class="sidebar-title">Most Commented Posts</h3>
            
              {% get_most_commented_posts as most_commented_posts %}
              <ul>
              {% for post in most_commented_posts %}
              <li>
              <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
              
              </li>
              {% endfor %}
              </ul>

              </div>
              
              <h3 class="sidebar-title">Categories</h3>
              <div class="sidebar-item categories">
                
              </div><!-- End sidebar categories-->





              
              <div class="sidebar-item tags">
                
                {% if tag %}
                Posts tagged with "{{ tag.name }}"
                {% endif %}</h3>



                <h3 class="sidebar-title">Tags:{{ post.tags.all|join:", " }}</h3>
                {% for post in posts %}
                
                <div class="sidebar-item tags">
              
                {% for tag in post.tags.all %}
                <ul>
                <li><a href="{% url 'blog:blogIndex_by_tag' tag.slug %}">{{tag.name | capfirst  }}</a></li>
                </ul>
                {% if not forloop.last %},{% endif %}

                {% endfor %}

               <!----> 
              </div><!-- End sidebar tags-->
              {% endfor %}

              
            </div><!-- End sidebar -->

          </div><!-- End blog sidebar -->

        </div>

      </div>
    </section><!-- End Blog Section -->

  </main><!-- End #main -->

  <!-- ======= Footer ======= -->
 
    {% include 'fragments/footer.html' %}
  {% endblock%}

templates/blog/latest_posts.html
{% load blog_tags %}

<ul style="text-decoration: none;">
{% for post in latest_posts %}



<div class="sidebar-item recent-posts">
    <div class="post-item clearfix">
<p style="text-align:center; margin-right: 50px;">
    <a href="{{ post.get_absolute_url}}">
        <img src="{{ post.blockImage.url }}" alt=""> {{post.title}}
    </a>
    
   
        {{post.created }}
    </p>
</div>


{% endfor %}
</ul>

templates/blog/pagination.html
{% extends 'fragments/base.html' %}
{% block content %}
<div class="blog-pagination">
    <ul class="justify-content-center">
      <li class="disabled"><i class="icofont-rounded-left"></i></li>
      
      {% if page.has_previous %}
      <a href="?page={{page.previous_page_number}}">Previous &nbsp;</a>
      {% endif %}

      <span class="current">
          Page {{page.number}} &nbsp; of &nbsp; {{page.paginator.num_pages}}

      </span>
      {% if page.has_next %}
      <a href="?page={{page.next_page_number}}"> &nbsp; Next <i class="icofont-rounded-right"></i> </a>
      {% endif %}
    </ul>
  </div>
  {% endblock %}

templates/blog/postDetail.html
{% extends 'fragments/base.html' %}

{% load blog_tags %}

{% block content %}
 {% include 'fragments/nav.html' %}
 
<main id="main">

    <!-- ======= Breadcrumbs ======= -->
    <section id="breadcrumbs" class="breadcrumbs">
      <div class="container">

        <div class="d-flex justify-content-between align-items-center">
          <h2>Blog</h2>
          <ol>
            <li><a href="/">Home</a></li>
             
            <li> <a href="{% url 'blog:blogIndex' %}">Blog</a></li>
          </ol>
        </div>

      </div>
    </section><!-- End Breadcrumbs -->

    <!-- ======= Blog Section ======= -->
    <section id="blog" class="blog">
      <div class="container">

        <div class="row">

          <div class="col-lg-8 entries">
                
            <article class="entry" data-aos="fade-up">
               

              <div class="entry-img">
                <img src="{{ post.blockImage.url }}" alt="" height="400px" width="800px">
                <img src="assets/img/blog-1.jpg" alt="" class="img-fluid">
              </div>

              <h2 class="entry-title">
                {% block title %}{{post.title| capfirst}}{% endblock%}
              </h2> &nbsp;
              <!--<h2 class="entry-title"> Category: -->
                <!--{{post.category | capfirst}}-->
              </h2>
              <div class="entry-meta">
                <ul>
                  <li class="d-flex align-items-center"><!-- <i class="icofont-user"></i> <a href="blog-single.html">{{post.author.email}} --><!-- </a></li>  -->

                </i> <a href="blog-single.html">{{post.author}}-{{post.author.id}} </a></li>


                {% if user.is_authenticated %}

                {% if user.id == post.author.id %}
                <li><i class="fa fa-pencil-square-o" aria-hidden="true"></i><a href="{% url 'blog:update_post' post.pk%}">Edit Post</a></li>


                 <li><i class="fa fa-trash" aria-hidden="true"></i><a href="{% url 'blog:deletepost' post.pk %}">Delete Post</a></li>
                 
                  {% endif %}

                  
                {% endif %}

                   <li class="d-flex align-items-center"><i class="icofont-user"></i> <a href="#">{{post.title}}</a></li>
                  
                  
                  <li class="d-flex align-items-center"><i class="icofont-wall-clock"></i> <a href="blog-single.html"><time datetime="2020-01-01">Jan 1, 2020</time></a></li>
                  <li class="d-flex align-items-center"><i class="icofont-comment"></i> <a href="blog-single.html">12 Comments</a></li>
                </ul>
                <hr/>
              </div>

              <div class="entry-content">
                <p class="justify" style="text-align:justify">
                 {{post.body|markdown}}
                </p>
                <div class="read-more">
                  <a href="{% url 'blog:post_share'  post.id %}">Share this post </a>
                  
                </div>

                {% with comments.count as total_comments %}
        <h2>
        {{ total_comments }} comment{{ total_comments|pluralize }}
              </h2>
              {% endwith %}
     {% for comment in comments %}
        <div class="comment">
          <p class="info">
         Comment {{ forloop.counter }} by {{ comment.name }}
        {{ comment.created }}
        </p>
          {{ comment.body|linebreaks }}
            </div>
          {% empty %}
          <p>There are no comments yet.</p>
          {% endfor %}
<!-- Adding comment form-->
          {% if new_comment %}
          <h2>Your comment has been added.</h2>
          {% else %}
          <h2>Add a new comment</h2>
          <form method="post">
          {{ comment_form.as_p }}
          {% csrf_token %}
          {{ form.media }}
          {{ form.as_p }}
          <p><input type="submit" value="Add comment"></p>
          </form>
          {% endif %}

              </div>

            </article><!-- End blog entry -->


            <div class="blog-pagination">
              <ul class="justify-content-center">
                <li class="disabled"><i class="icofont-rounded-left"></i></li>
                <li><a href="#">1</a></li>
                <li class="active"><a href="#">2</a></li>
                <li><a href="#">3</a></li>
                <li><a href="#"><i class="icofont-rounded-right"></i></a></li>
              </ul>
            </div>

          </div><!-- End blog entries list -->

          <div class="col-lg-4">

            <div class="sidebar" data-aos="fade-left">

              <h3 class="sidebar-title">Search</h3>
              <div class="sidebar-item search-form">
               
                <form action="{% url 'blog:search' %}" method=POST>
                  {% csrf_token %}
                  <input type="search" class = "form-control " name="searched"  placeholder="search post">
                  <button type="submit"><i class="icofont-search"></i></button>
                </form>
              </div><!-- End sidebar search formn-->

              <h3 class="sidebar-title">Recent Posts</h3>
              <div class="sidebar-item recent-posts">
                <div class="post-item clearfix">
                  
                  {% show_latest_posts 5 %}
                  
                </div>


               

              </div><!-- End sidebar recent posts-->

              <h3 class="sidebar-title">Tags</h3>
              <div class="sidebar-item tags">
                <ul>
                  <li><h2>Similar posts</h2>
                    {% for post in similar_posts %}
                    <p>
                    <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                    </p>
                    {% empty %}
                    There are no similar posts yet.
                    {% endfor %}</li>
                  
                </ul>

              </div><!-- End sidebar tags-->
              
              <div class="post-item clearfix">
                <h3 class="sidebar-title">Most Commented Posts</h3>
            
              {% get_most_commented_posts as most_commented_posts %}
              <ul class="text-decoration-none">
              {% for post in most_commented_posts %}
              <li>
              <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
              </li>
              {% endfor %}
              </ul>

              </div>
            </div><!-- End sidebar -->

          </div><!-- End blog sidebar -->

        </div>

      </div>
    </section><!-- End Blog Section -->

  </main><!-- End #main -->

  <!-- ======= Footer ======= -->
 
    {% include 'fragments/footer.html' %}
  {% endblock%}